SocialBlog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from authy.views import UserProfile, UserProfileFavorites, follow

urlpatterns = [
    path('admin/', admin.site.urls),
    path('post/', include('post.urls')),
    path('user/', include('authy.urls')),
    path('notifications/', include('notifications.urls')),
    path('<username>/', UserProfile, name='profile'),
    path('<username>/saved', UserProfile, name='profilefavorites'),
    path('<username>/follow/<option>', follow, name='follow'),
    path('oauth/', include('social_django.urls', namespace='social')),
    path('accounts/', include('allauth.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

notifications/urls.py
from django.urls import path
from notifications.views import ShowNOtifications, DeleteNotification


urlpatterns = [
   	path('', ShowNOtifications, name='show-notifications'),
   	path('<noti_id>/delete', DeleteNotification, name='delete-notification'),

]

post/urls.py
from django.urls import path
from post.views import index, NewPost, PostDetails, tags, like, favorite,PostDelet,Allusers


urlpatterns = [
   	path('', index, name='index'),
   	path('<uuid:post_id>/delet',PostDelet,name='postdelet'),
   	path('newpost/', NewPost, name='newpost'),
   	path('<uuid:post_id>', PostDetails, name='postdetails'),
   	path('<uuid:post_id>/like', like, name='postlike'),
   	path('<uuid:post_id>/favorite', favorite, name='postfavorite'),
   	path('tag/<slug:tag_slug>', tags, name='tags'),
   	path('allusers',Allusers,name='allusers'),
]

notifications/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Notification(models.Model):
	NOTIFICATION_TYPES = ((1,'Like'),(2,'Comment'), (3,'Follow'))

	post = models.ForeignKey('post.Post', on_delete=models.CASCADE, related_name="noti_post", blank=True, null=True)
	sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name="noti_from_user")
	user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="noti_to_user")
	notification_type = models.IntegerField(choices=NOTIFICATION_TYPES)
	text_preview = models.CharField(max_length=90, blank=True)
	date = models.DateTimeField(auto_now_add=True)
	is_seen = models.BooleanField(default=False)

authy/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from authy.models import Profile

def ForbiddenUsers(value):
	forbidden_users = ['admin', 'css', 'js', 'authenticate', 'login', 'logout', 'administrator', 'root',
	'email', 'user', 'join', 'sql', 'static', 'python', 'delete']
	if value.lower() in forbidden_users:
		raise ValidationError('Invalid name for user, this is a reserverd word.')

def InvalidUser(value):
	if '@' in value or '+' in value or '-' in value:
		raise ValidationError('This is an Invalid user, Do not user these chars: @ , - , + ')

def UniqueEmail(value):
	if User.objects.filter(email__iexact=value).exists():
		raise ValidationError('User with this email already exists.')

def UniqueUser(value):
	if User.objects.filter(username__iexact=value).exists():
		raise ValidationError('User with this username already exists.')

class SignupForm(forms.ModelForm):
	username = forms.CharField(widget=forms.TextInput(), max_length=30, required=True,)
	email = forms.CharField(widget=forms.EmailInput(), max_length=100, required=True,)
	password = forms.CharField(widget=forms.PasswordInput())
	confirm_password = forms.CharField(widget=forms.PasswordInput(), required=True, label="Confirm your password.")
	first_name = forms.CharField(widget=forms.TextInput(), max_length=30, required=True,)

	class Meta:

		model = User
		fields = ('username', 'email', 'password','first_name')

	def __init__(self, *args, **kwargs):
		super(SignupForm, self).__init__(*args, **kwargs)
		self.fields['username'].validators.append(ForbiddenUsers)
		self.fields['username'].validators.append(InvalidUser)
		self.fields['username'].validators.append(UniqueUser)
		self.fields['email'].validators.append(UniqueEmail)

	def clean(self):
		super(SignupForm, self).clean()
		password = self.cleaned_data.get('password')
		confirm_password = self.cleaned_data.get('confirm_password')

		if password != confirm_password:
			self._errors['password'] = self.error_class(['Passwords do not match. Try again'])
		return self.cleaned_data

class ChangePasswordForm(forms.ModelForm):
	id = forms.CharField(widget=forms.HiddenInput())
	old_password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'input is-medium'}), label="Old password", required=True)
	new_password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'input is-medium'}), label="New password", required=True)
	confirm_password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'input is-medium'}), label="Confirm new password", required=True)

	class Meta:
		model = User
		fields = ('id', 'old_password', 'new_password', 'confirm_password')

	def clean(self):
		super(ChangePasswordForm, self).clean()
		id = self.cleaned_data.get('id')
		old_password = self.cleaned_data.get('old_password')
		new_password = self.cleaned_data.get('new_password')
		confirm_password = self.cleaned_data.get('confirm_password')
		user = User.objects.get(pk=id)
		if not user.check_password(old_password):
			self._errors['old_password'] =self.error_class(['Old password do not match.'])
		if new_password != confirm_password:
			self._errors['new_password'] =self.error_class(['Passwords do not match.'])
		return self.cleaned_data

class EditProfileForm(forms.ModelForm):
	picture = forms.ImageField(required=False)
	first_name = forms.CharField(widget=forms.TextInput(), max_length=50, required=False)
	last_name = forms.CharField(widget=forms.TextInput(), max_length=50, required=False)
	location = forms.CharField(widget=forms.TextInput(), max_length=25, required=False)
	url = forms.URLField(widget=forms.TextInput(), max_length=60, required=False)
	profile_info = forms.CharField(widget=forms.TextInput(), max_length=260, required=False)

	class Meta:
		model = Profile
		fields = ('picture', 'first_name', 'last_name', 'location', 'url', 'profile_info')

post/forms.py
from django import forms
from post.models import Post

class NewPostForm(forms.ModelForm):
	image = forms.ImageField(required=True)
	caption = forms.CharField(widget=forms.Textarea(attrs={'class': 'summernote'}), required=True)
	tags = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control inputtags','type':'text','placeholder':'Add COMMA(,) to saperate tags'}), required=True)
	title = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control '}), required=True)
	class Meta:
		model = Post
		fields = ('image', 'caption', 'tags','title')	


		

notifications/views.py
from django.shortcuts import render, redirect
from django.template import loader
from django.http import HttpResponse

from notifications.models import Notification
# Create your views here.

def ShowNOtifications(request):
	user = request.user
	notifications = Notification.objects.filter(user=user).order_by('-date')
	Notification.objects.filter(user=user, is_seen=False).update(is_seen=True)

	template = loader.get_template('notification1.html')

	context = {
		'notifications': notifications,
	}

	return HttpResponse(template.render(context, request))

def DeleteNotification(request, noti_id):
	user = request.user
	Notification.objects.filter(id=noti_id, user=user).delete()
	return redirect('show-notifications')


def CountNotifications(request):
	count_notifications = 0
	if request.user.is_authenticated:
		count_notifications = Notification.objects.filter(user=request.user, is_seen=False).count()

	return {'count_notifications':count_notifications}
	

def ShowNotPreview(request):
	user = request.user
	notification = Notification.objects.filter(user=user).order_by('-date')
	Notification.objects.filter(user=user, is_seen=False).update(is_seen=True)

	return{'notification':notification}

SocialBlog/templates/allusers.html
{% extends 'base.html' %}

{% load static %}
{% load humanize %}

{% block content %}
  <div class="main-content">
        <section class="section">
          <div class="section-body">
            


            <div class="row"><!--row-->
              {% for profile in profile %}
               <div class="col-12  col-lg-4">
                <div class="card author-box card-primary">
                  <div class="card-body">
                    <div class="author-box-left">
                      {% if profile.picture %}
                      <img alt="image" src="{{profile.picture.url}}" class="rounded author-box-picture">
                      {% else %}
                      <img alt="image" src="https://bulma.io/images/placeholders/96x96.png" class="rounded author-box-picture">
                      {% endif %}

                      <div class="clearfix"></div>
                      
                    </div>
                    <div class="author-box-details">
                      <div class="author-box-name">
                        <a href="{% url 'profile' profile.user %}">{{profile.user.username}}</a>
                      </div>
                      
                      
                      
                      <div class="float-right mt-sm-0 mt-3">
                        <a href="{% url 'profile' profile.user %}" class="btn">View Profile <i class="fas fa-chevron-right"></i></a>
                      </div>
                    </div>
                  </div>
                </div>
                    </div>
               
                  {% endfor %}

                </div><!--row-->



            </div>
          </section>
        </div>

{% endblock %}

SocialBlog/templates/change_password.html
{% extends 'base.html' %}
{% load static %}

        
{% block content %}

<div class="row center-align">
    <form method="post" action="" role="form" class="col s12">
    </h3>
      <div class="row">
        {% csrf_token %}
        {{ form.id }}
        <h3>Change password</h3>
        <div class="input-field col s12">
          {{ form.old_password }}
          <label for="old_password">Old password</label>
        </div>
      </div>
        <div class="row">
        <div class="input-field col s12">
          {{ form.new_password }}
          <label for="new_password">New password</label>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s12">
          {{ form.confirm_password }}
          <label for="password">Re-type password</label>
        </div>
      </div>
      <div class="row">
        <div class="col s12">
          <span style="color: red; font-weight: bold;">{{ form.errors }}</span>
        </div>
      </div>
      <button class="btn waves-effect waves-light" type="submit" name="action"><i class="material-icons left">send</i>Change Password</button>
    </form>
  </div>

{% endblock %}

SocialBlog/templates/change_password_done.html
{% extends 'base.html' %}

{% block content %}

<div class="row">
	<br>
	<br>
	<br>
	<br>
	<div class="col s12 center-align">
		<i class="large material-icons green-text">check_circle</i>
	</div>
	<div class="col s12 center-align">
		<h4>Your password has been succesfully changed</h4>
	</div>


</div>

<br>
<br>
{% endblock %}

SocialBlog/templates/create-post.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<div class="main-content">
        <section class="section">
          <div class="section-body">
 <div class="row">
              <div class="col-12">
                <div class="card">
                  <div class="card-header">
                    <form method="post" action="" enctype="multipart/form-data" role="form">
    {% csrf_token %}
                    <h4>Full Summernote</h4>
                  
                 

                  <div class="form-group row mb-4">
                      <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Blog Poster</label>
                      <div class="col-sm-12 col-md-7">
                         <span style="color:black">Tap Below to Select an Image</span>
                        <div id="imagePreview" class="image-preview" style="display: flex;align-items: center;justify-content: center;width: 100%">
                         
                          <img src="{% static 'assest/img/facebook.svg' %}" alt="" id="output"  class="image-preview__image  img-fluid rounded mx-auto d-block " style="width: 100%">

                           <input type="file" name="image" accept="image/*" onchange="loadFile(event)" required id="id_image">
                      </div>
                             


                          </div>
                        

                  <div class="card-body">
                    <div class="form-group row mb-4">
                      <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Title</label>
                      <div class="col-sm-12 col-md-7">
                        <div style="border:1px solid #C1C1C1">
                        
                        {{form.title}}
                          </div>

                      </div>
                    </div>
                    <div class="form-group row mb-4">
                      <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Tags</label>
                      <div class="col-sm-12 col-md-7">
                        <div style="border:1px solid #C1C1C1">
                      {{form.tags}}
                     
                      </div>
                     

                      </div>

                    </div>
                    <div class="form-group row mb-4">
                      <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Content</label>
                      <div class="col-sm-12 col-md-7">
                        {{form.caption}}
                      </div>
                    </div>
                    <div class="form-group row mb-4">
                      <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3"></label>
                      <div class="col-sm-12 col-md-7">
                        <button class="btn btn-primary">Publish</button>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>

</form></div></div></div></div></div></section></div>





<img id="output"/>
<script>
  var loadFile = function(event) {
    var output = document.getElementById('output');
    output.src = URL.createObjectURL(event.target.files[0]);
    output.onload = function() {
      URL.revokeObjectURL(output.src) // free memory
    }
  };
</script>
        
{% endblock %}

SocialBlog/templates/edit_profile.html
{% extends 'base.html' %}
{% load static %}

        
{% block content %}

      <!-- Main Content -->
  <div class="main-content">
        <section class="section">
          <div class="section-body">

                     <div class="tab-pane fade  show active" id="settings" role="tabpanel"  aria-labelledby="profile-tab2">
                         <form method="post" enctype="multipart/form-data" action="" role="form">
                           {% csrf_token %}

                          <div class="card-header">
                            <h4>Edit Profile</h4>
                          </div>
                          <div class="card-body">

                            
   <h6 style="display: flex;justify-content: center;align-items: center;">Tap to chango profile picture</h6>  

          <div id="imagePreview" class="image-preview" style="margin-left: auto;margin-right:auto;margin-bottom: 10px;display: flex;justify-content: center;align-items: center;">
                         {% if profile.picture is True %}
                          <img src="{{ profile.picture.url }}" alt="" id="output"  class="image-preview__image  img-fluid rounded mx-auto d-block " >
                          {% else %}
                          <img src="" alt="" id="output"  class="image-preview__image  img-fluid rounded mx-auto d-block " >
                          {% endif %}
                             <input type="file" name="picture" accept="image/*" id="id_picture"  onchange="loadFile(event)"  >
                           
                      </div>
                        
                            <div class="row">
                              <div class="form-group col-md-6 col-12">
                                <label>First Name</label>
                                <input type="text" class="form-control" >
                                <div class="invalid-feedback">
                                    {{ form.first_name }}
                                </div>
                              </div>
                              <div class="form-group col-md-6 col-12">
                                <label>Last Name</label>
                                <input type="text" class="form-control" >
                                <div class="invalid-feedback">
                                    {{ form.last_name }}
                                </div>
                              </div>
                            </div>
                            <div class="row">
                              <div class="form-group col-md-7 col-12">
                                <label>City</label>
                                <input type="Text" class="form-control" >
                                <div class="invalid-feedback">
                                  {{ form.location }}
                                </div>
                              </div>
                              <div class="form-group col-md-5 col-12">
                                <label>Website Url(optional)</label>
                                <input type="url" class="form-control" >
                                <div class="invalid-feedback">
                                  {{ form.url }}
                                </div>
                              </div>
                            </div>
                            <div class="row">
                              <div class="form-group col-12">
                                <label>Personal Info</label>
                                <input type="text" class="form-control" >
                                <div class="invalid-feedback">
                                  {{ form.profile_info }}
                                </div>
                              </div>
                            </div>
                           
                                </div>
                              </div>
                            </div>
                          </div>
                          <div class="card-footer text-right">
                            <button type="submit" value="login" class="btn btn-success">Save Changes</button>
                         
                </div>
              </div>
            </div>
          </div>

        </section>

</div>

</form></div></div></section></div>



<script>
  var loadFile = function(event) {
    var output = document.getElementById('output');
    output.src = URL.createObjectURL(event.target.files[0]);
    output.onload = function() {
      URL.revokeObjectURL(output.src) // free memory
    }
  };
</script>




  

{% endblock %}

SocialBlog/templates/index1.html
{% extends 'base.html' %}

{% load static %}
{% load humanize %}

{% block content %}
     

{% for post_item in post_items %}
  <div class="card">
  <div class="card-image">
    <figure class="image is-4by3">
      <a href="{{ post_item.get_absolute_url }}"><img src="{{ post_item.picture.url }}" alt="Placeholder image"></a>
    </figure>
  </div>
  <div class="card-content">
    <div class="media">
      <div class="media-left">
        <figure class="image is-48x48">
          {% if post_item.user.profile.picture %}
            <img src="{{ post_item.user.profile.picture.url }}" alt="Placeholder image">
          {% else %}
            <img src="https://bulma.io/images/placeholders/96x96.png" alt="Placeholder image">
          {% endif %}
        </figure>
      </div>
      <div class="media-content">
        {% if post_item.user.profile.first_name %}
          <a href="{% url 'profile' post_item.user %}"><p class="title is-4">{{ post_item.user.profile.first_name }} {{ post_item.user.profile.last_name }}</p></a>
        {% else %}
          <a href="{% url 'profile' post_item.user %}"><p class="title is-4">Unknown</p></a>
        {% endif %}

        <p class="subtitle is-6">@{{ post_item.user.username }}</p>

      {{ post_item.caption }}
      <p>{% for tag in post_item.tags.all %}<a href="{{ tag.get_absolute_url }}">#{{ tag }}</a>{% endfor %}</p>
      <br>
      <strong><small>{{ post_item.posted | naturaltime }}</small></strong>
      </div>
    

    <div class="media-right">
      <a href="#{% url 'postlike' post_item.id %}"><i class="material-icons has-text-danger">favorite</i></a>
      <p>{{ post_item.likes }} Likes</p>  
    </div>

</div>



  </div>
</div>

<br>

{% endfor %}

</div>
</div>

{% endblock %}

SocialBlog/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">


<!-- Mirrored from www.radixtouch.in/templates/admin/otika/source/light/auth-login.html by HTTrack Website Copier/3.x [XR&CO'2014], Sat, 23 Jan 2021 08:15:38 GMT -->
<head>
  <meta charset="UTF-8">
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no" name="viewport">
  <title>Otika - Admin Dashboard Template</title>
  <!-- General CSS Files -->
  <link rel="stylesheet" href="{% static 'assets/css/app.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets/bundles/bootstrap-social/bootstrap-social.css' %}">
  <!-- Template CSS -->
  <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
  <link rel="stylesheet" href="{% static 'assets/css/components.css' %}">
  <!-- Custom style CSS -->
  <link rel="stylesheet" href="{% static 'assets/css/custom.css' %}">
  <link rel='shortcut icon' type='image/x-icon' href="{% static 'assets/img/favicon.ico' %}" />
</head>

<body>
  <div class="loader"></div>
  <div id="app">
    <section class="section">
      <div class="container mt-5">
        <div class="row">
          <div class="col-12 col-sm-8 offset-sm-2 col-md-6 offset-md-3 col-lg-6 offset-lg-3 col-xl-4 offset-xl-4">
            <div class="card card-primary">
              <div class="card-header">
                <h4>Login</h4>
              </div>
              <div class="card-body">
                 <form method="post" action="" role="form">
                    {% csrf_token %}
                  <div class="form-group">
                    <label for="email">Username</label>
                    
                    <input type="text" name="username" class="form-control" autofocus autocapitalize="none" autocomplete="username" maxlength="150" required id="id_username">





                      <div class="invalid-feedback">
                      Please fill in your email
                    </div>
                  </div>
                  <div class="form-group">
                    <div class="d-block">
                      <label for="password" class="control-label">Password</label>
                      <div class="float-right">
                        <a href="auth-forgot-password.html" class="text-small">
                          Forgot Password?
                        </a>
                      </div>
                    </div>
                    <input type="password" name="password" class="form-control" autocomplete="current-password" required id="id_password">
                    <div class="invalid-feedback">
                      please fill in your password
                    </div>
                  </div>
                  
                  </div>
                  <div class="form-group" style="padding: 20px">
                    <button type="submit" class="btn btn-primary btn-lg btn-block" tabindex="4">
                      Login
                    </button>
                  </div>
                </form>
                <div class="text-center mt-4 mb-3" >
                  <div class="text-job text-muted">Login With Social</div>
                </div>
                <div class="row sm-gutters" style="padding: 20px">
                  <div class="col-6">
                    <a href="{% url 'social:begin' 'facebook' %}" class="btn btn-block btn-social btn-facebook">
                      <span class="fab fa-facebook"></span> Facebook
                    </a>
                  </div>
                  <div class="col-6">
                    <a class="btn btn-block btn-social btn-google">
                      <span class="fab fa-google"></span> Google
                    </a>
                  </div>
                </div>
              </div>
              <div class="mt-5 text-muted text-center">
              Don't have an account? <a href="{% url 'signup' %}">Create One</a>
            </div>  
            </div>
            
          </div>
        </div>
      </div>
    </section>
  </div>
  <!-- General JS Scripts -->
  <script src="{% static 'assets/js/app.min.js' %}"></script>
  <!-- JS Libraies -->
  <!-- Page Specific JS File -->
  <!-- Template JS File -->
  <script src="{% static 'assets/js/scripts.js' %}"></script>
  <!-- Custom JS File -->
  <script src="{% static 'assets/js/custom.js' %}"></script>
</body>


<!-- Mirrored from www.radixtouch.in/templates/admin/otika/source/light/auth-login.html by HTTrack Website Copier/3.x [XR&CO'2014], Sat, 23 Jan 2021 08:15:38 GMT -->
</html>

SocialBlog/templates/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">


<!-- Mirrored from www.radixtouch.in/templates/admin/otika/source/light/auth-register.html by HTTrack Website Copier/3.x [XR&CO'2014], Sat, 23 Jan 2021 08:32:41 GMT -->
<head>
  <meta charset="UTF-8">
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no" name="viewport">
  <title>Otika - Admin Dashboard Template</title>
  <!-- General CSS Files -->
  <link rel="stylesheet" href="{% static 'assets/css/app.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets/bundles/bootstrap-social/bootstrap-social.css' %}">
  <!-- Template CSS -->
  <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
  <link rel="stylesheet" href="{% static 'assets/css/components.css' %}">
  <!-- Custom style CSS -->
  <link rel="stylesheet" href="{% static 'assets/css/custom.css' %}">
  <link rel='shortcut icon' type='image/x-icon' href="{% static 'assets/img/favicon.ico' %}" />
</head>

<body>
  <div class="loader"></div>
  <div id="app">
    <section class="section">
      <div class="container mt-5">
        <div class="row">
          <div class="col-12 col-sm-10 offset-sm-1 col-md-8 offset-md-2 col-lg-8 offset-lg-2 col-xl-8 offset-xl-2">
            <div class="card card-primary" style="background-color: #FFFFFF">
              <div class="card-header">
                <h4>Register</h4>

               
              </div>
              <div class="card-body">
                <form method="post" action="" role="form">
                  {% csrf_token %}
                  <div class="row">
                    <div class="form-group col-6">
                      <label for="frist_name">Username</label>
                      <input id="id_username" type="text" class="form-control" required maxlength="30" name="username" autofocus>
                    </div>
                    <div class="form-group col-6">
                      <label for="last_name">First Name</label>
                       <input type="text" name="first_name" class="form-control" maxlength="30" required id="id_first_name">
                    </div>
                  </div>
                  <div class="form-group">
                    <label for="email">Email</label>
                    <input id="id_email" type="email" class="form-control" name="email"  required maxlength="100">
                    <div class="invalid-feedback">
                    </div>
                  <div class="row">
                    <div class="form-group col-6">
                      <label for="password" class="d-block">Password</label>

                      <input id="id_password" type="password" class="form-control pwstrength" data-indicator="pwindicator"
                        name="password" required >

                         <div id="pwindicator" class="pwindicator">
                        <div class="bar"></div>
                        <div class="label"></div>
                      </div>
                    </div>
                    <div class="form-group col-6">
                      <label for="password2" class="d-block">Password Confirmation</label>

                      <input required id="id_confirm_password" type="password" class="form-control" name="confirm_password">

                   

                    </div>
                  </div>
                  <div class="form-group">
                    <div class="custom-control custom-checkbox">
                      <input type="checkbox" name="agree" class="custom-control-input" id="agree">
                      <label class="custom-control-label" for="agree">I agree with the <a href="">terms and conditions</a></label>

                                <span style="color: red; font-weight: bold;">{{ form.errors }}</span>

                    </div>
                  </div>
                  <div class="form-group" style="display: flex;justify-content: center;align-items: center;">
                    <button type="submit" class="btn btn-danger btn-lg"  name="action" style="width: 50%" >
                      Register
                    </button>

                   



                  </div>
                </form>
              </div>
              <div class="mb-4 text-muted text-center">
                Already Registered? <a href="auth-login.html">Login</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>
  <!-- General JS Scripts -->
  <script src="{% static 'assets/js/app.min.js' %}"></script>
  <!-- JS Libraies -->
  <script src="{% static 'assets/bundles/jquery-pwstrength/jquery.pwstrength.min.js' %}"></script>
  <script src="{% static 'assets/bundles/jquery-selectric/jquery.selectric.min.js' %}"></script>
  <!-- Page Specific JS File -->
  <script src="{% static 'assets/js/page/auth-register.js' %}"></script>
  <!-- Template JS File -->
  <script src="{% static 'assets/js/scripts.js' %}"></script>
  <!-- Custom JS File -->
  <script src="{% static 'assets/js/custom.js' %}"></script>
</body>


<!-- Mirrored from www.radixtouch.in/templates/admin/otika/source/light/auth-register.html by HTTrack Website Copier/3.x [XR&CO'2014], Sat, 23 Jan 2021 08:32:41 GMT -->
</html>